"""Test derivation from acceptance criteria.

derive_tests_for_spec() returns a dict mapping filename to pytest source code.
One file is produced per spec, named test_derived_{sanitized_name}.py.

Every AcceptanceCriterion produces at least one test function whose name
encodes the criterion's id (AC7). Criteria with input_pattern=None are
emitted as @pytest.mark.skip stubs (spec edge case).
"""
from __future__ import annotations

import re
from typing import TYPE_CHECKING, Literal

from jinja2 import Environment

if TYPE_CHECKING:
    from sddkit.models.spec import Spec

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_IDENTIFIER_RE = re.compile(r"[^a-zA-Z0-9]+")
_LEADING_DIGIT_RE = re.compile(r"^\d")


def _sanitize(text: str) -> str:
    """Return a lowercase identifier-safe version of text."""
    result = _IDENTIFIER_RE.sub("_", text).strip("_").lower()
    if _LEADING_DIGIT_RE.match(result):
        result = "s_" + result
    return result or "unnamed"


def _ac_function_name(ac_id: str, ac_text: str) -> str:
    """Produce a pytest function name encoding the AC identifier."""
    id_part = _sanitize(ac_id)
    # First six words of text for context, truncated to keep names reasonable.
    words = re.split(r"\s+", ac_text.strip())[:6]
    text_part = _sanitize("_".join(words))[:60]
    return f"test_{id_part}_{text_part}".rstrip("_")


def _output_filename(spec_name: str) -> str:
    return f"test_derived_{_sanitize(spec_name)}.py"


# ---------------------------------------------------------------------------
# Jinja2 template for the generated test module
# ---------------------------------------------------------------------------

_ENV = Environment(autoescape=False, keep_trailing_newline=True)
_ENV.filters["ac_function_name"] = lambda ac: _ac_function_name(ac["id"], ac["text"])

_TEMPLATE = _ENV.from_string(
    '''\
"""Tests derived from acceptance criteria for spec: {{ spec_name }}.

Auto-generated by sddkit.derive_tests(). Each function corresponds to one
acceptance criterion. Functions for criteria without an input_pattern are
marked skip until a pattern is defined.

Do not edit this file by hand — re-generate from the Spec object instead.
"""

from __future__ import annotations

import pytest

{% for ac in criteria %}
{% if ac.input_pattern is not none %}
def {{ ac | ac_function_name }}() -> None:
    """{{ ac.id }}: {{ ac.text }}

    Input pattern: {{ ac.input_pattern }}
    """
    raise NotImplementedError("Test stub for {{ ac.id }} — implement against the acceptance criterion above.")


{% else %}
@pytest.mark.skip(reason="{{ ac.id }} has no input_pattern; define a pattern in the spec before implementing.")
def {{ ac | ac_function_name }}_stub() -> None:
    """{{ ac.id }}: {{ ac.text }}"""
    pass


{% endif %}
{% endfor %}
'''
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def derive_tests_for_spec(
    spec: "Spec",
    framework: Literal["pytest"] = "pytest",
) -> dict[str, str]:
    criteria = [
        {
            "id": ac.id,
            "text": ac.text,
            "input_pattern": ac.input_pattern,
        }
        for ac in spec.acceptance_criteria
    ]
    source = _TEMPLATE.render(spec_name=spec.name, criteria=criteria)
    filename = _output_filename(spec.name)
    return {filename: source}
